### ISSUE TITLE
Where do you pick your node version

### ISSUE THREAD

**Issue by apechimp** [airtonix/bash-dot-files#1]
I'm looking to see how you solved [this](https://github.com/creationix/nvm/issues/110#issuecomment-66872329), but it's not clear to me where you've done that.

**Comment by airtonix** [comment]
Instead of overriding `cd` or `node` I utilise the builtin command to render the prompt.

Therein, you can run commands.

I don't yet auto switch versions for node, but I would be doing it there: https://github.com/airtonix/bash-dot-files/blob/master/.bash_profile#L21

It's a list of function names to execute each time a prompt is to be rendered.

So you'd create a function that checks the PWD for a `.project` file, then if it exists, run `nvm use $NODE_VERSION` or something similar.

I'm not super keen on modifying expected behaviour of `cd` or `node`. Probably because i've not yet explored or been shown why it might be a good idea.
